name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
      - users: actions/checkout@v3
      - name: install deps
        run: python print('Зависимости установлены')
       
