name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Checkout
        run: pip install -r backend/requirements.txt
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: install deps
        working-directory: ./backend
        run: pip install -r requirements.txt
      - name: Test
        run: |
          cd backend
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python -m pytest tests/test_api.py -v
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        run: echo ${{secrets.Test}}
