name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Checkout
        run: pip install -r requirements.txt
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Checkout
        run: pip install -r requirements.txt
      - name: Test
        run: python -m pytest tests/test_api.py

       
